### ISSUE TITLE
[SNCU Support] Move reports to ETL

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/SNCU#43]
Support ticket - https://avni.freshdesk.com/a/tickets/2294

- [ ] Update all the following reports to use ETL and remove error if any -

https://docs.google.com/spreadsheets/d/15U3mOkcVjHhXlr318uj8DRQNzC6mBOTf-GEPf9SLfTM/edit#gid=1150649020

**Comment by nupoorkhandelwal** [comment]
Estimates - Since this a card on which reword of checking and fixing the reports is being done, remaining estimate is 3-4 hrs approx

**Comment by AchalaBelokar** [comment]
- [ ] Children milestone report
old report
![Screenshot 2023-05-10 at 2.10.52 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/1833aca0-f7ab-48a0-966d-8ac821a4a1f7)


new report
![Screenshot 2023-05-10 at 2.12.17 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/93256354-1e39-4fd6-ae52-ae891118e888)

**Comment by AchalaBelokar** [comment]
[ ] Cohort wise report
- Month6_status_normal is mismatch with old one by 1
- Month12_status_exited
- there are other mismatch also
-![Screenshot 2023-05-10 at 2.44.22 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/9aa3f89c-fbcf-4e24-9cfd-92bed0ff1acc) 


![Screenshot 2023-05-10 at 3.04.18 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/1bdec15f-6fce-41b8-bc7d-c3a612328da6)

**Comment by AchalaBelokar** [comment]
- [ ] Immunisation of Children no mismatch 
![Screenshot 2023-05-10 at 3.31.19 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/c7251992-e1de-491d-a479-063214093194)

![Screenshot 2023-05-10 at 3.31.36 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/f0ddf057-45f3-46e9-b797-ca5d585cb859)

**Comment by AchalaBelokar** [comment]
- [ ] KMC Care
![Screenshot 2023-05-10 at 3.41.18 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/bcc9f926-8938-4f27-9e8e-b23e989ef34b)

![Screenshot 2023-05-10 at 3.41.37 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/3fde5a04-1e1c-46e0-a85f-975e6d53fbc5)

**Comment by BEULAHEVANJALIN** [comment]
Aggregate:

- [x] Child Death
- [x] Child growth monitoring
- [x] Child growth monitoring 7 months to 5 years 
- [x] Child - Morbidity Status Within 0-59 Days
- [x] Children milestone report
- [x] Cohort wise report
- [x] Growth Monitoring (nutritional status)
- [x] Immunisation of Children
- [x] KMC Care
- [x] Newborn care
- [x] Registration Form based reports
- [x] Registration of children
- [x] SNCU Form based reports
- [ ] Task generated and task completed

Linelists:

- [x] Child - Morbidity Status for Children 0-59 days Linelist
- [x] Child - Program Exit Linelist
- [x] Child PNC Linelist
- [x] Child wise linelist report
- [x] Growth Monitoring(nutritional status) Linelist
- [x] Linelist for child growth monitoring
 
---
- [x] Linelist for child growth monitoring 7 month to 5 years
- [x] Linelist for fully immunised children
- [x] Linelist for immunisation of children
- [x] Linelist for KMC Care
- [x] Linelist for milestone report
- [x] Linelist for registration form based reports
- [x] Linelist for SNCU form based report
- [ ] Task generated child nutrition

**Comment by BEULAHEVANJALIN** [comment]
Generic queries:
https://gist.github.com/BEULAHEVANJALIN/7a2d6ad2514bc99954b1ff8013bc080e

**Comment by nupoorkhandelwal** [comment]
ETA - 7 days.

**Comment by nupoorkhandelwal** [comment]
select * from program_enrolment where id in(    122276,
    122626);
Need to get right address for these individuals.

**Comment by Dinesh2019** [comment]
- [x] count mismatch for children milestone report - Able to stand up with holding something
- [x] count mismatch for children milestone report - Able to start walking few steps
- [x] Growth Monitoring (nutritional status) - while applying date filter data shows zero
- [x] Immunisation of Children - while applying filter getting this error "There was an error on the server. Try again or contact site administrators. (Error UID: 415af8df-7b2d-4828-ada7-38bfba65a9f4)" filter i used and address."Block" = 'Valia' and address."PHC" = 'Kara' and address."Subcenter" = 'Luna' and address."Village" = 'Luna'
- [x] KMC Care data mismatch of Proportion and Number of children with LBW with the mandatory date filter '2023-07-11'::date and '2023-09-08'
- [x] Newborn care - getting this error while appying the filter There was an error on the server. Try again or contact site administrators. (Error UID: a4de4ea7-73f0-4492-8239-60eaeaa63224) used filter  and block = 'Netrang' and phc = 'Thava' and subcenter = 'Netrang-2' and village =  'Netrang-2'
- [x] Registration Form based reports- getting this error There was an error on the server. Try again or contact site administrators. (Error UID: 6fe8835e-fae3-465d-86de-106537f09e43) by applying the same filter 
- [x] Registration of children applying the date filter as "2023-08-01" and "2023-09-01" the count is mismatched between jasper and database
- [x] SNCU Form based reports - Weight at time of Discharge - for block Dediyapada count mismatch and also for start date and end date filter (2023-08-01 and 2023-09-20)
- [x] SNCU Form based reports - Discharge Criteria - for block Dediyapada count mismatch also for date filter
- [x] SNCU Form based reports - Did child cry immedately after birth - for block Dediyapada count mismatch also for date filter
- [x] SNCU Form based reports - Congenital Anomaly - for block Dediyapada count mismatch also for date filter
- [x] SNCU Form based reports - Child's First visit - for block Dediyapada count mismatch also for date filter

**Comment by Gojo-Taqi** [comment]
- For the report KMC care, there is one individual which is giving incorrect value for indicator "No of children with LBW"

**Comment by Dinesh2019** [comment]
- [x] SNCU Form based reports - Weight at time of Discharge - Indicator 1.5-1.99 kg - in jasper 201 but in db 200 and also for >= 2.5 kg in jasper 179 but in db 178
https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdGpsIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7d4b15b13b6cb02b6802c234206fdace9c0d95f0/imgonline-com-ua-twotoone-gkt0VGNpJog6.jpg
and we also have the same issue for date filter 
https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdkhsIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2119b2d4e69e7fe789a8abcadb7562b12ad50897/imgonline-com-ua-twotoone-b5v6FswYOZ.jpg
- [x] SNCU Form based reports - Discharge Criteria - for block Dediyapada count mismatch also for date filter
- [x] SNCU Form based reports - Did child cry immedately after birth - for block Dediyapada count mismatch also for date filter
- [x] SNCU Form based reports - Congenital Anomaly - for block Dediyapada count mismatch also for date filter
- [x] SNCU Form based reports - Child's First visit - for block Dediyapada count mismatch also for date filter
- [x] Registration of children applying the date filter as "2023-08-01" and "2023-09-01" the count is mismatched between jasper and database and other feedback from QA when we apply filter instead of null can we display as zero if possible
https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ2JtIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--dd6f4f027c25edb6071496f86d529174a410847c/Screenshot%202023-09-28%20at%2012.15.15%20PM.png
- [x] Registration Form based reports - count get mismatched for Number of family members when apply the filter as Dediyapada and also table disappears when applying the filter which doesn't have the value.
- [x] Registration Form based reports  - Very poor family - count mismatch when we apply the filter as Dediyapada
- [x] Registration Form based reports  - Mother's education- count mismatch when we apply the filter as Dediyapada
- [x] Registration Form based reports - Caste - count mismatch when we apply the filter as Dediyapada
- [x] Registration Form based reports -Religion - count mismatch when we apply the filter as Dediyapada
- [x] Newborn care - count mismatch when we apply the date filter

**Comment by Dinesh2019** [comment]
Can we fix this issue? 

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUlFQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ab85093f14efa07d676928504b29d05288b413c8/Screen%20Recording%202023-10-04%20at%207.52.44%E2%80%AFPM.mov
