### ISSUE TITLE
[SNCU] Child PNC form

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/SNCU#5]
https://docs.google.com/spreadsheets/d/1DJzjWi_Pde0pDQLdDNTzG3QkrJZ1MREs/edit#gid=633620735

Form changes
Visit scheduling

**Comment by garimadosar5** [comment]
QA Notes - 
- FEG - "First examination" is not showing for PNC 1. Case - Bindu Nayak. **Fixed**

- Counselling points are not showing. **Added**
1. Child PNC - Registration Immunisation - Dos
2. Weight counselling
3. Hygiene counselling
4. Breastfeeding counselling
5. Baby warming counselling

- PNC is getting scheduled till 6 months of age of child. Case - Surbhi Jaiswal
**DOB - 19-08-2020,
PNC 1 - 13-10-2020, Completed on 14-08-2020
PNC 2 - 11-11-2020  but this was completed on 14-08-2020
Since during second visit, child was less than 2 months so PNC 3 got scheduled for 03-December. 
Ideally a visit scheduled for November, wont get completed in mid October!!**

**Comment by garimadosar5** [comment]
**QA Notes - 2**
- FEG - "First examination" is showing for second PNC visit. - Case - Bindu Nayak
Question - Did the child pass stool and urine within 24 hrs? **Fixed**
- Please sync and check case - Bindu Nayak.
check PNC 3 form and its scheduled date. **Fixed** **Issue was -- editing PNC 1 generated next visit PNC 3. Fixed this. On editing an exiting/completed visit no new visit is getting scheduled now.**
